### ISSUE TITLE
Beta Releases push to main styleguide build

### ISSUE THREAD

**Issue by landondurnan** [square/maker#105]
**Describe the bug**

It appears that pushes to the beta branch update the main styleguide release so that the `latest` is the same code as beta.

**Expected behavior**

Ideally, pre-releases don't trigger an override on the `latest` styleguide build.

**Reproduction steps (incl. Browser and OS)**

https://square.github.io/maker/styleguide/latest/#/ is currently showing an older non-master release. For example, there is a new Container component that isn't documented and several other components are documenting changes from `beta`

**Comment by privatenumber** [comment]
Code is a lot different from the last time I worked with it. I think @pretzelhammer is better suited for this.

I'm thinking `latest` should never exist as it's a semver alias, and not actually representative of a static version. If anything `latest` should just be a redirect but probably simpler to just remove it. Instead, it should all just be branch names if not versions.

I am doing an overhaul on the Orbit end to have a similar setup so I can revisit all of this later to be much cleaner.

**Comment by landondurnan** [comment]
Should be resolved here: https://github.com/square/maker/pull/111 we'll see the updates in the next versioned release
