### ISSUE TITLE
Support accessory slots in MContainer

### ISSUE THREAD

**Issue by ericghpham** [square/maker#115]
### Feature request

I'd like to request support for an "accessory" slot for the `Section` component. `@market/web` contains an equivalent in [`MarketRow`](https://market-storybook.s3.amazonaws.com/0.34.0-beta/index.html?path=/docs/components-market-row--with-leading-accessory)

<img width="392" alt="Screen Shot 2021-08-25 at 12 15 44 PM" src="https://user-images.githubusercontent.com/20484187/130870424-7eb3b4a7-b697-482d-a100-f7b3c12aaf12.png">

### Why?

The driving motivation is to use `Section` to implement the new Loyalty Rewards Dialog UI ([figma](https://www.figma.com/file/o89XEbl7CkZK2SwfAEp6S4/Text-message-marketing-on-Square-Online-opt-in?node-id=233%3A1958)) in the Checkout Flow
<img width="392" alt="Screen Shot 2021-08-25 at 12 15 44 PM" src="https://user-images.githubusercontent.com/20484187/130870371-c1b5b587-221d-43f1-9adc-320ad3ce504f.png">

This also sounded like a pattern that could be useful for other consumers, and would be a non-breaking change ([slack](https://square.slack.com/archives/C01HXVA3G4E/p1629919122087800))

### Alternatives

Currently we don't have a better alternative than to create a one-off component that wraps around `Section`, which would be sufficient for our use case

**Comment by pretzelhammer** [comment]
renamed this issue title because MSection has been renamed to MContainer, and the former is also going to be removed in the next major version of Maker, v6

**Comment by pretzelhammer** [comment]
I think we should just make an MList or MDescriptionList component for this, I don't see why someone would need or want to create a list of MContainers, that's not what they're really supposed to be used for.
