### ISSUE TITLE
version numbers in styleguide out of order

### ISSUE THREAD

**Issue by ashjtan** [square/maker#124]
### Bug description

On  the [styleguide](https://square.github.io/maker/), the version numbers are in alphabetical order. However, that has placed `4.9.1` at the bottom while `4.10.0` is over by `4.1.4` because of the '1' digit.

It makes it difficult to find Maker versions once they hit multi digits.

### Reproduction

Go to https://square.github.io/maker/

### Environment

```shell
n/a
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by ashjtan** [comment]
We could simply implement something like [this solution](https://stackoverflow.com/questions/40201533/sort-version-dotted-number-strings-in-javascript) to replace [this sort](https://github.com/square/maker/blob/master/build/generate-deploy-index/index.js#L38).

**Comment by pretzelhammer** [comment]
Maker already pulls in the npm [semver](https://github.com/npm/node-semver) package which can correctly compare semantic version numbers to greater accuracy than that SO answer (because it can also handle pre-release versions) so if we update the sort we should use the semver dep.

**Comment by pretzelhammer** [comment]
If anyone has some spare time they can assign this issue to themselves to claim working on it. If it doesn't get done this week I'll probably have some spare time in the next 2 weeks where I could do it but it's simple enough that anyone can take it.
