### ISSUE TITLE
remove deprecated and redundant MSection component from library

### ISSUE THREAD

**Issue by ashjtan** [square/maker#127]
### Bug description

While the MSection has been deprecated in favor of the MContainer since v4.8.0, this has not been indicated in the styleguide.

### Reproduction

https://square.github.io/maker/styleguide/latest/#/Section

### Environment

```shell
n/a
```

### Can you contribute a fix?

- [X] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
@ashjtan rather than marking it deprecated, let's just outright remove it if we don't need it (at least for now, in its current incarnation). You can make it a breaking change and we'll just do a major version release for v6.

**Comment by pretzelhammer** [comment]
resolved: https://github.com/square/maker/pull/148
