### ISSUE TITLE
Dialog / Modal components do not have reactive props

### ISSUE THREAD

**Issue by Ryguy11** [square/maker#143]
### Bug description

When opening a maker dialog or maker modal component with a render function has props passed in, i.e.
`const { default: DialogComponent } = await import('./DialogComponent.vue');
this.dialogApi.open(h => h(DialogComponent, {
 props: {
  label: this.reactiveLabel,
 },
}));`
the `props` object is not reactive once the modal or dialog is open. 

### Reproduction

See above code snippet. An easy example would be to `$emit` an event from the dialog/modal component back to the opening component. The event changes the local state of `reactiveLavel` which should be reflected on the open component's prop `label` but it is not.

### Environment

```shell
"@square/maker": "^4.12.0",
"vue": "^2.6.12",
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by Ryguy11** [comment]
This seems like a similar situation: https://forum.vuejs.org/t/how-do-i-make-props-reactive-when-creating-components-with-createelement/59574

**Comment by pretzelhammer** [comment]
I feel like we had this exact issue in Orbit, can't remember what the recommended workaround was. cc: @privatenumber @landondurnan @lokesh do any of you remember?

**Comment by pretzelhammer** [comment]
I think I've come across a fix for this while working on the ToastLayer component, after I'm done with that I'll try to port the fix over to the BladeLayer, DialogLayer, and ModalLayer components. It probably won't require any breaking changes. Probably.
