### ISSUE TITLE
[Actionbar] Reduce padding at standalone mode

### ISSUE THREAD

**Issue by sohnj877** [square/maker#169]
### Feature request

We should remove the extra deadclick padding on the actionbar when site is running in standalone mode.

### Why?

Extra padding is unnecessary since the standalone mode hides browser UI.

### Additional context

![Screen Shot 2021-10-22 at 1 31 03 PM](https://user-images.githubusercontent.com/7245055/138501994-0b9e7977-c91b-4001-9ba1-18f460009807.png)

https://user-images.githubusercontent.com/7245055/138502040-de8499ce-fd00-4290-9a6c-5f1a44c9044d.mp4

**Comment by landondurnan** [comment]
I'm going to make an attempt on this. I had a version here (https://github.com/square/maker/pull/80) but code conflicts prevented merge at the time.

**Comment by lokesh** [comment]
@landondurnan Is `env(safe-area-inset-*)` not working because of our implementation, or is it not a viable option to solve our problem? If it is viable, are there examples online using the css property that we can test?

**Comment by landondurnan** [comment]
Resolved in 6.3.1
