### ISSUE TITLE
Popover Component

### ISSUE THREAD

**Issue by tatems** [square/maker#172]
### Figma link

https://www.figma.com/file/Fz10ZinFDOWgXlukmJjXKm/Maker-playground?node-id=4178%3A63689

### Description

The goal here is to build out a set of components to provide a way to display more contextual information or actions that can be triggered by an action from another component. Inspiration for these components comes from the [Orbit UI Popover](https://github.com/squareup/orbit-ui/tree/master/src/components/Popover).

The overall functionality of this component should be similar to the Orbit counterpart. The main requirements are:

- Be triggered by an action that could be inside or outside the `o-popover` component.
- The popover should 'tether' itself to the element that triggers it (most of the time)
  - Unlike Orbit, this component should be able to be triggered from elsewhere in the DOM, and be able to be tethered to another element entirely
- The tethered component should be able to re-position itself to stay in view
- The popover content should conform to some height/width/scroll behaviours (detailed in the Figma)

### API

In most cases, this will be the most common implementation pattern for the popover:
```html
<template>
  <m-popover>
    <!-- this action slot will be the element the popover will tether to -->
    <template #action="popover">
      <m-button @click="popover.toggle()">
        Popover Toggle
      </m-button>
    </template>

    <!-- Option #1 automatically put this content in the container -->
    <template #content>
      Some content here
    </template>

    <!-- Option #2 For more customizability, have consumers put the container in -->
    <template #content>
      <m-popover-container>
        Some content here
      </m-popover-container>
    </template>
  </m-popover>
</template>
```

However, it will be necessary to expose a way to trigger the popover from _outside_ the popover component context:

```html
<template>
  <div>
    <m-button @click="togglePopover()">
      Popover Toggle
    </m-button>
  </div>

  <div ref="popoverTether">
    Tether to me!
  </div>

  <m-popover
    ref="popover"
    :tether-element="popoverTether"
  >
    <template #content>
      Some content here
    </template>
  </m-popover>
</template>

<script>
export default {
  ...
  mounted() {
    this.someEventBus.$on('someTrigger', () => this.$refs.popover.open());
  },

  methods: {
    togglePopover() {
      this.$refs.popover.toggle();
    },
  },
};
</script>
```

### Theme support

At this point in time, we will be supporting light and dark themes.
![image](https://user-images.githubusercontent.com/3402466/139260774-b8e9b62f-1e8a-4ac2-9b1d-f2d6f75d2a3d.png)

**Comment by tatems** [comment]
Questions/Feedback:
1. Yeah I was thinking being a little more explicit would be better for readability/clarity on what is happening.
2. The `PopoverContainer` would be the visual box itself. The reason I was thinking it might be better to explicitly use it is so we could allow consumers to define their own container with different styles while still maintaining the popover functionality.
3. I can explore that, though I don't know if that _really_ applies here. The portal idea would be great to handle mobile (dialog) vs desktop (regular popover) views for content. `tetherElement` input would just define what that regular popover gets attached to.
4. Yup, we definitely need the layering handler.

**Comment by landondurnan** [comment]
1. 👍 
2. I think the "Popover" parent container can do that job and not require a child component.
3. The popover will wrap the element it's "tethered" to so an additional prop isn't necessary to define that element.
