### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by tatems** [square/maker#173]
### Figma link

https://www.figma.com/file/Fz10ZinFDOWgXlukmJjXKm/Maker-playground?node-id=4179%3A63356

### Description

Implement a Menu/Select component. This component will be used along side #172 to provide a more stylized alternative to the native `select` element.

### API

Generally, the quickest/easiest pattern to implement would be to just expose an `options` prop with a standard interface that is used to populate the menu options.

However, since more visual elements and functionality are planned for this component, it would be better to provide a very basic default layout, and allow more flexibility by exposing the default. This way, we can add new functionality with less risk of breaking previous usages.

```html
<template>
  <!-- By default, if all you need is a menu with basic string values, you can just use `MMenu` without the slot -->
  <m-menu
    v-model="basicValue"
    :options="basicOptions"
  />

  <!-- if the data you're using is more complex, you can use the slot to customize the data -->
  <m-menu
    v-model="complexValue"
    :options="complexOptions"
  >
    <template #default="{ option, isSelected }">
      <m-menu-option
        :value="option.value"
        :is-selected="isSelected"
      >
        <m-menu-option-label>{{ option.label }}</m-menu-option-label>
      </m-menu-option>
    </template>
  </m-menu>
</template>

<script>
export default {
  data() {
    return {
      basicValue: undefined,
      basicOptions: ['Option 1', 'Option 2', 'Option 3'],
      complexValue: undefined,
      complexOptions: [
        { value: 1, label: 'Option 1' },
        { value: 2, label: 'Option 2' },
        { value: 3, label: 'Option 3' },
      ],
    };
  },
};
</script>
```

### Theme support

Currently, we will support light and dark themes
![image](https://user-images.githubusercontent.com/3402466/139276079-4407f0fb-2467-42b3-a300-22b9e87106de.png)

**Comment by landondurnan** [comment]
Going to suggest we hold off on eng review / development until popover is complete as that will be the internal component and any external API considerations will likely be additive to what the popover offers.

**Comment by pretzelhammer** [comment]
A Menu component has been released in Maker so I'm closing this issue: https://square.github.io/maker/styleguide/latest/#/Menu
