### ISSUE TITLE
Choice :selected prop change does not change internal currentValue

### ISSUE THREAD

**Issue by tatems** [square/maker#200]
### Bug description

If the input value `:selected` on `MChoice` is updated programmatically, the internal state is not updated to reflect that change and the incorrect choice is highlighted (or no choice is highlighted at all if the initial value was `undefined`).

### Reproduction

Reproduction here: https://codesandbox.io/s/mchoice-state-bug-0hehv

### Environment

```shell
System:
    OS: macOS 11.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 591.24 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
  npmPackages:
    @square/maker: ^5.4.0 => 5.4.0 
    vue: ^2.6.12 => 2.6.12 
    webpack: ^5.1.3 => 5.1.3 
```
```


### Addressed by

_No response_

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
closing as this has been fixed
