### ISSUE TITLE
Add closeOnClickOutside behavior to the Dialog component

### ISSUE THREAD

**Issue by JimRottinger** [square/maker#207]
### Feature request

The [Modal component](https://github.com/square/maker/blob/88e05e6913da3efbe0193eb8105aac817e0e2cd6/src/components/Modal/README.md) has a configurable option to close itself if clicking outside of itself. I would like to use that same behavior in a dialog.

### Why?

Tapping or clicking outside of a dialog to close it is a common behavior that we should support.

**Comment by landondurnan** [comment]
Added in https://github.com/square/maker/pull/208
