### ISSUE TITLE
Text button 'g' is cut off at the bottom

### ISSUE THREAD

**Issue by kevinlee11** [square/maker#252]
### Bug description

The text button uses a line of height of 1 which appears to cause the `g` here to be slightly truncated at the bottom:
![image](https://user-images.githubusercontent.com/18740390/158645115-6fd56bd9-5624-4300-94b4-3133382041cc.png)

### Reproduction

Create a text button that includes the letter `g` using the default medium size

### Environment

```shell
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.80 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  npmPackages:
    @square/maker: ^7.0.0 => 7.0.0 
    vue: ^2.6.14 => 2.6.14 
    webpack: ^5.37.0 => 5.38.1
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
closing, pr was merged
