### ISSUE TITLE
No outline on focus-visible tabbing on Text Button

### ISSUE THREAD

**Issue by kevinlee11** [square/maker#254]
### Bug description

If you tab into a Text Button (:focus-visible) you don't get the accessibility outline colour because of the outline being set to none.
![image](https://user-images.githubusercontent.com/18740390/158683219-56582f99-a8e6-4c2c-8a12-74e5baeb70d8.png)

Expected without that property:
![image](https://user-images.githubusercontent.com/18740390/158683313-ad92a862-ce2d-4e76-965b-673cee07605e.png)

### Reproduction

Tab into the Text Button and you won't get the accessibility outline colour.

### Environment

```shell
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.80 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
  npmPackages:
    @square/maker: ^7.0.0 => 7.0.0 
    vue: ^2.6.14 => 2.6.14 
    webpack: ^5.37.0 => 5.38.1
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
closing, pr was merged
