### ISSUE TITLE
Maker Inputs Autofill handling

### ISSUE THREAD

**Issue by sonatata** [square/maker#332]
### Feature request

When users have saved information on their browser, autofill will render input fields as such on Chrome: 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/22898829/169545349-7a2876ce-9e99-4687-b639-64645d941fa7.png">

### Why?

Would be nice to have the Maker Input and Select components handle this rather than the consumer

### Alternatives

adding this fixes the issue for chrome on the consumer side for inputs
```
  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus, 
  input:-webkit-autofill:active{
      -webkit-box-shadow: 0 0 0 30px var(--neutral-0) inset !important;
      -webkit-text-fill-color: var(--neutral-100) !important;
  }
```

**Comment by pretzelhammer** [comment]
closing as i believe this was fixed in this merged pr: https://github.com/square/maker/pull/382
