### ISSUE TITLE
default-theme is passing a fontFamily for fontWeight in Headline Pattern

### ISSUE THREAD

**Issue by bashunaimiroy** [square/maker#341]
This causes MTheme to reject it, causing problems in our Typography Feature. ([Internal Square Link](https://sentry.io/organizations/square-inc/issues/?project=1281397&query=is%3Aunresolved+undefined+Invalid+value&statsPeriod=14d))

https://github.com/square/maker/blob/f9a6a07a09c1c1a9d620b8660eaa259d4bceae22/src/components/Theme/src/default-theme.js#L127

**Comment by pretzelhammer** [comment]
closing as pr was merged
