### ISSUE TITLE
Speed up button transitions

### ISSUE THREAD

**Issue by lokesh-squareup** [square/maker#38]
**Is your feature request related to a problem? Please describe.**
Noticing there is an ease-in on the entering transition for the tertiary button background color. It makes it feel a little sluggish as it disconnects the mouse enter from the appearance of the background color.

**Describe the solution you'd like**
Make it snappier:
1. Reducing time to 150ms
2. Invert the easing: Rather than ease-in, accelerate out.

![image](https://user-images.githubusercontent.com/72631144/111382726-90da2880-8664-11eb-9c68-876dcf95e84f.png)

**Describe alternatives you've considered**
n/a

**Comment by lokesh-squareup** [comment]
Is it possible to assign this to me? The issue options in the right column are disabled for me

**Comment by pretzelhammer** [comment]
Lokesh left, closing this.
