### ISSUE TITLE
auto clean-up lab & styleguide deploys

### ISSUE THREAD

**Issue by pretzelhammer** [square/maker#45]
Creating a PR currently creates a new styleguide deploy, but when the PR is merged or closed the styleguide deploy is never cleaned up, so this issue requires creating (or updating?) and existing github workflow to auto cleanup lab & styleguide deploys when their corresponding PRs get closed or merged

**Comment by privatenumber** [comment]
Directory cleaning aside, I'm curious what impact this will have on the git history when someone tries to git clone. eg. does each CI action get slower and slower?

**Comment by privatenumber** [comment]
Maybe tap into the [`closed` event on pull_request](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request).

**Comment by pretzelhammer** [comment]
completed in this pr https://github.com/square/maker/pull/331
