### ISSUE TITLE
Image components are attaching sourceset properties in the wrong order

### ISSUE THREAD

**Issue by mattmewton** [square/maker#457]
### Bug description

Right now in Maker, the `src` property in the `Image.vue` component precedes the `srcset` and `sizes` property. In order to take full advantage of sourceset, the order of properties needs to be as follows.

```
srcset
sizes
src
```

The expected property order can be viewed in the [responsive images guide on MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_different_sizes).

### Reproduction

Viewed the [Image.vue code here](https://github.com/square/maker/blob/master/src/components/Image/src/Image.vue#L21) to observe

### Environment

This affects all environments

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
thank for filing this issue! a PR has been opened with the fix here: https://github.com/square/maker/pull/458
