### ISSUE TITLE
[Button] Text is cut off

### ISSUE THREAD

**Issue by sohnj877** [square/maker#471]
### Bug description

letter "g" is cut off
<img width="174" alt="Screen Shot 2022-10-20 at 5 44 18 PM" src="https://user-images.githubusercontent.com/7245055/197064944-c1b52047-d2a6-47ee-9630-77d606efd093.png">

### Reproduction

Create a button with "Change" text

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.27 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
```

### Addressed by

Oct 26, 2022

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by pretzelhammer** [comment]
@sohnj877 can you clarify what props you're using with the button? is this a `small`, `medium`, or `large` button? also, what version of Maker are you on?

**Comment by sohnj877** [comment]
@pretzelhammer `small`, `15.2.0`
