### ISSUE TITLE
bug: missing utils/transitions

### ISSUE THREAD

**Issue by privatenumber** [square/maker#55]
**Describe the bug**

`utils/transitions.js` is missing from package versions [v3.0.0](https://unpkg.com/browse/@square/maker@3.0.0/utils/) and [v4.0.0](https://unpkg.com/browse/@square/maker@4.0.0/utils/). It's present in [v2.2.4 (the version before)](https://unpkg.com/browse/@square/maker@2.2.4/utils/).

When building:
```
ERROR in ./node_modules/@square/maker/components/Modal/script.js
Module not found: Error: Can't resolve '../../utils/transitions' in '/Users/osame/Documents/ecom-github/weebly/website-springboard/node_modules/@square/maker/components/Modal'

ERROR in ./node_modules/@square/maker/components/TransitionFadeIn/script.js
Module not found: Error: Can't resolve '../../utils/transitions' in '/Users/osame/Documents/ecom-github/weebly/website-springboard/node_modules/@square/maker/components/TransitionFadeIn'

ERROR in ./node_modules/@square/maker/components/TransitionSpringUp/script.js
Module not found: Error: Can't resolve '../../utils/transitions' in '/Users/osame/Documents/ecom-github/weebly/website-springboard/node_modules/@square/maker/components/TransitionSpringUp'

ERROR in ./node_modules/@square/maker/utils/Transition/script.js
Module not found: Error: Can't resolve '../../utils/transitions' in '/Users/osame/Documents/ecom-github/weebly/website-springboard/node_modules/@square/maker/utils/Transition'
```

**Expected behavior**

For `utils/transitions.js` to exist.

**Reproduction steps (incl. Browser and OS)**

- Can't reproduce locally
- Seems to be happening on GH actions

**When does this need to be addressed by?**

**Which version are you using? Did this work in previous versions?**

**Which version of Vue.js are you using? Did this work in previous versions?**

**Comment by privatenumber** [comment]
### Relevant links
#### v3.0.0
PR: https://github.com/square/maker/pull/41
Release logs: https://github.com/square/maker/runs/2249349049?check_suite_focus=true

#### v4.0.0
PR: https://github.com/square/maker/pull/47
Release logs: https://github.com/square/maker/runs/2249395456?check_suite_focus=true


### Observations

Both release logs show that `utils/transitions.js` was built:

```
Child
    Hash: cb93081400e15ea9e468
    Time: 3266ms
    Built at: 04/01/2021 8:26:16 PM
                 Asset      Size  Chunks                   Chunk Names
        transitions.js  4.34 KiB       0  [emitted]        main
    transitions.js.map  14.5 KiB       0  [emitted] [dev]  main
    Entrypoint main = transitions.js transitions.js.map
    [0] external "stylefire" 42 bytes {0} [built]
    [1] external "popmotion" 42 bytes {0} [built]
    [2] ./utils/transitions.js 5.73 KiB {0} [built]
```

However, it doesn't seem included when publish` is executed by `semantic-release`.

Also seems to be the case based on the Package size report, which doesn't run npm publish, but uses npm's publish file detection logic.

**Comment by privatenumber** [comment]
I added an action that just builds, lists output files, and dry-runs publish. Seems sometimes it's outputted, sometimes it's not (perhaps there's a race condition happening?).

Run where `transitions.js` was outputted:
https://github.com/square/maker/runs/2251267923?check_suite_focus=true

Run where it wasn't:
https://github.com/square/maker/runs/2251248804?check_suite_focus=true

**Comment by privatenumber** [comment]
Removed clean-webpack-plugin:

- https://github.com/square/maker/runs/2251876193?check_suite_focus=true

**Comment by pretzelhammer** [comment]
This happened before for `utils/assert` in a couple random Maker releases! Thanks for making this issue and fixing it, it was super annoying.
