### ISSUE TITLE
Actionbar overlay on dark backgrounds

### ISSUE THREAD

**Issue by landondurnan** [square/maker#62]
**Describe the bug**
The actionbar overlay hardcodes a white to transparent gradient. This looks fine on most light colored backgrounds, but if the background is dark it looks really odd. 

![CleanShot 2021-04-13 at 13 27 00](https://user-images.githubusercontent.com/129122/114616651-f87f9580-9c5b-11eb-8cd6-8ad86f3bd9ce.png)

**Expected behavior**
This is likely to convert into a feature request in order to resolve the bug, but one potential solution would be the ability to pass the background color to the actionbar so the gradient more closely matches what the overlay.

**Reproduction steps (incl. Browser and OS)**

Use actionbar on a black / dark background

**When does this need to be addressed by?**

Being reported by production users, so asap.

**Which version are you using? Did this work in previous versions?**

Current

**Which version of Vue.js are you using? Did this work in previous versions?**

Current

**Comment by pretzelhammer** [comment]
How do you feel about:
- Getting rid of the transparent-to-white gradient bg entirely?
- Adding a prop to ActionBar like `onDarkBackdrop` which toggles the gradient bg to be transparent-to-black?
- Making the gradient bg transparent-to-some-CSS-var where it defaults to white but and users of ActionBar can set the CSS var to override it to any color?
- Doing the same as above except using a Vue prop instead of a CSS var.

**Comment by landondurnan** [comment]
You described every scenario I was thinking about as a potential solution. I think some of it requires some conversation with design and thoughts about future-proofing. But gut feel is the first one is obviously the easiest.  The last three are all more dependent on theming direction. We could add something now and deprecate it later.

**Comment by pretzelhammer** [comment]
Discussed this with Design on a video call and settled on removing the transparent-to-white gradient bg for now and revisiting it when we have color theming in Maker.

**Comment by privatenumber** [comment]
FYI this was originally from Shimaa's designs. But as long as she's aware, all good.

**Comment by landondurnan** [comment]
Released
